### ISSUE TITLE
Update on LuaRocks

### ISSUE THREAD

**Issue by karai17** [kikito/i18n.lua#15]
The version of this module on LuaRocks seems to be very old. Would it be possible to make a new release on LuaRocks?

**Comment by Pashugan** [comment]
I'm joining the question.

**Comment by istr** [comment]
Created PR #16 to address this.

**Comment by kikito** [comment]
Hi there,

I have updated the rockspec to 0.9.1 and released a new luarock. I didn't accept @istr's PR, and I will explain there.

Keep in mind that one of the things I want to do with this library before releasing 1.0 is [removing the global state](https://github.com/kikito/i18n.lua/issues/12). This means that the interface will need to change.

For now, however, this issue is closed.
